
services:
  web:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 81:81
    networks:
      - network1
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8000:8000
    networks:
      - network1
networks:
  network1: