services:
  web:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - network1
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - network1
networks:
  network1: